# Generated by Django 5.1.6 on 2025-03-07 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 255 characters or fewer.', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='username'),
        ),
    ]
