# Generated by Django 5.1.6 on 2025-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deskripsiadmin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='fileadmin',
            field=models.FileField(blank=True, null=True, upload_to='admin_files/'),
        ),
    ]
