# Generated by Django 5.1.6 on 2025-03-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_deskripsiadmin_request_fileadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='assigned_to',
        ),
    ]
